homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.7094
  longitude: 5.1916
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

#logger:
#  default: debug

system_health:

http:
  #api_password: 5076CK27
  base_url: https://hasspa.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:

# # Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
# logbook:

# recorder:
  # purge_keep_days: 5
  # db_url: mysql://hass:5076CK27@core-mariadb/homeassistant

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

switch:
  - platform: rpi_pfio
    ports:
      0:
        name: Zonnescherm uit
      1:
        name: Zonnescherm in
      2:
        name: Relais 3
      3:
        name: Relais 4
      4:
        name: Relais 5
      5:
        name: Relais 6
  
binary_sensor:
  - platform: rpi_pfio
    ports:
      3:
        name: Schakelaar_1
        settle_time: 50
      1:
        name: Schakelaar_2
        settle_time: 50
      2:
        name: Schakelaar_4
        settle_time: 50
      0:
        name: Schakelaar_6
        settle_time: 50
      5:
        name: Schakelaar_3
        settle_time: 50
      4:
        name: Schakelaar_5
        settle_time: 50

        
cover:
  - platform: template
    covers:
      zonnescherm:
        friendly_name: "Zonnescherm"
        optimistic: true
        # value_template: >-
          # {% if is_state('cover.bedroom', 'open') %}
            # open
          # {% elif is_state('cover.livingroom', 'open') %}
            # open
          # {% else %}
            # closed
          # {% endif %}
        open_cover:
          - service: switch.turn_off
            data:
              entity_id: switch.zonnescherm_in
          - service: switch.turn_on
            data:
              entity_id: switch.zonnescherm_uit
          - delay: 0:01:00
          - service: switch.turn_off
            data:
              entity_id: switch.zonnescherm_uit
        close_cover:
          - service: switch.turn_off
            data:
              entity_id: switch.zonnescherm_uit
          - service: switch.turn_on
            data:
              entity_id: switch.zonnescherm_in
          - delay: 0:01:00
          - service: switch.turn_off
            data:
              entity_id: switch.zonnescherm_in
        stop_cover:
          - service: switch.turn_off
            data:
              entity_id: switch.zonnescherm_in
          - service: switch.turn_off
            data:
              entity_id: switch.zonnescherm_uit
              
input_boolean:
  verlichting_woonkamer:
    name: Verlichting woonkamer
    initial: off
  koken:
    name: Koken
    initial: off
  keukentafel:
    name: Keukentafel
    initial: off
  kast:
    name: Kast
    initial: off
  douchen:
    name: Douchen
    initial: off
  toilet:
    name: Toilet
    initial: off
  eettafel_hoog:
    name: Eettafel hoog
    initial: off
  eettafel_laag:
    name: Eettafel laag
    initial: off
    
rest_command:
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'
    
timer:
  toilet:
    duration: '00:10:00'