- alias: "Mode on"
  trigger:
    - platform: state
      entity_id: input_select.mode
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'True'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'Auto'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: 'auto'

- alias: "Mode auto - Home"
  trigger:
    - platform: state
      entity_id: input_select.mode
    - platform: state
      entity_id: device_tracker.android618bdafece7c66a8
    - platform: state
      entity_id: device_tracker.samsunggalaxys7
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'Auto'
    - condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.android618bdafece7c66a8
        state: 'home'  
      - condition: state
        entity_id: device_tracker.samsunggalaxys7
        state: 'home'        
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'Auto'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: 'auto'

- alias: "Mode auto - Away"
  trigger:
    - platform: state
      entity_id: input_select.mode
    - platform: state
      entity_id: device_tracker.android618bdafece7c66a8
    - platform: state
      entity_id: device_tracker.samsunggalaxys7
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'Auto'
    - condition: state
      entity_id: device_tracker.android618bdafece7c66a8
      state: 'not_home'  
    - condition: state
      entity_id: device_tracker.samsunggalaxys7
      state: 'not_home'        
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'False'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: 'off'
    - service: light.turn_off
      entity_id:
       - light.verlichting_speelkamer_level
       
- alias: "Mode off"
  trigger:
    - platform: state
      entity_id: input_select.mode
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'False'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'False'        
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: 'off'
    - service: light.turn_off
      entity_id:
       - light.verlichting_speelkamer_level
       
- alias: "Auto lichtsterkte binnen"
  trigger:
    - platform: state
      entity_id: sensor.sensor_woonkamer_luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      below: 50
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
  action:
    - service: light.turn_on
      entity_id:
       - light.verlichting_woonkamer_schemerlampen_level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek
      data_template:
        brightness: '{{ 150 - (states("sensor.sensor_woonkamer_luminance") | int) }}'

- alias: "Auto lichtsterkte buiten"
  trigger:
    - platform: state
      entity_id: sensor.sensor_woonkamer_luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      below: 12
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
  action:
    - service: switch.turn_on
      entity_id:
       - switch.philio_technology_corporation_unknown_type0001_id0013_switch
       
- alias: "Lampen uit binnen"
  trigger:
    - platform: state
      entity_id: sensor.sensor_woonkamer_luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      above: 50
    - condition: state
      entity_id: input_select.mode_light
      state: 'False'
  action:
    - service: light.turn_off
      entity_id:
       - light.verlichting_woonkamer_schemerlampen_level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek

- alias: "Lampen uit buiten"
  trigger:
    - platform: state
      entity_id: sensor.sensor_woonkamer_luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      above: 12
    - condition: state
      entity_id: input_select.mode_light
      state: 'False'
  action:
    - service: switch.turn_off
      entity_id:
       - switch.philio_technology_corporation_unknown_type0001_id0013_switch
       
- alias: "Lampen volledig aan binnen"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'True'
  action:
    - service: light.turn_on
      entity_id:
       - light.verlichting_woonkamer_schemerlampen_level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek
      data: 
        brightness: 100
        
- alias: "Keukenlamp aan"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'True'
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
  action:
    - service: switch.turn_on
      entity_id:
       - switch.keuken
       
- alias: "Keukenlamp uit"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'False'
  action:
    - service: switch.turn_off
      entity_id:
       - switch.keuken

- alias: "Verwarming Fedde omhoog"
  trigger:
    - platform: time
      at: '17:00:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.babykamer_babykamer
        temperature: 18

- alias: "Verwarming Fedde omlaag"
  trigger:
    - platform: time
      at: '20:30:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.babykamer_babykamer
        temperature: 5
        
- alias: "Lamp speelkamer automatisch aan bij beweging"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      below: 12
    - condition: state
      entity_id: light.verlichting_speelkamer_level
      state: 'off'
  action:
    - service: light.turn_on
      entity_id:
       - light.verlichting_speelkamer_level

- alias: "Lamp speelkamer automatisch uit bij 5 min geen beweging"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.verlichting_speelkamer_level
      state: 'on'
  action:
    - service: light.turn_off
      entity_id:
       - light.verlichting_speelkamer_level
       
- alias: "Lampen woonkamer automatisch aan bij beweging"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      below: 12
    - condition: state
      entity_id: input_select.mode_light
      state: 'False'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'Auto'        

- alias: "Zwave heal"
  trigger:
    platform: time
    at: '2:30:00'
  action:
    service: zwave.heal_network
    
- alias: "Deurbel"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.deurbel'}
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        ringtone_id: 10
        ringtone_vol: 60
    - service: notify.rik
      data:
        message: 'Deurbel gaat'
        data:
          say:

- alias: "Trigger alarm bij armed away"
  trigger:
    - platform: state
      entity_id: binary_sensor.achterdeur_open
      to: 'on'
    - platform: state
      entity_id: binary_sensor.sensor_woonkamer_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.voordeur_open
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm

- alias: "Hond blaft bij alarm"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        ringtone_id: 8
        ringtone_vol: 8
    - service: notify.rik
      data:
        message: 'Alarm gaat af'
        data:
          say: