- alias: "Mode on"
  trigger:
    - platform: state
      entity_id: input_select.mode
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'True'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'Auto'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: 'auto'

- alias: "Mode auto - Home"
  trigger:
    - platform: state
      entity_id: input_select.mode
    - platform: state
      entity_id: device_tracker.android618bdafece7c66a8
    - platform: state
      entity_id: device_tracker.samsunggalaxys7
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'Auto'
    - condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.android618bdafece7c66a8
        state: 'home'  
      - condition: state
        entity_id: device_tracker.samsunggalaxys7
        state: 'home'        
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'Auto'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: 'auto'

- alias: "Mode auto - Away"
  trigger:
    - platform: state
      entity_id: input_select.mode
    - platform: state
      entity_id: device_tracker.android618bdafece7c66a8
    - platform: state
      entity_id: device_tracker.samsunggalaxys7
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'Auto'
    - condition: state
      entity_id: device_tracker.android618bdafece7c66a8
      state: 'not_home'  
    - condition: state
      entity_id: device_tracker.samsunggalaxys7
      state: 'not_home'        
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'False'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: 'off'
    - service: light.turn_off
      entity_id:
       - light.verlichting_speelkamer_level

- alias: "Simulation - Random on"
  trigger:
    platform: time
    at: '9:18:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'Sim'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'Auto'

- alias: "Simulation - Random off"
  trigger:
    platform: time
    at: '23:08:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'Sim'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'False'
       
- alias: "Mode off"
  trigger:
    - platform: state
      entity_id: input_select.mode
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode
      state: 'False'
    - condition: state
      entity_id: input_select.mode
      state: 'Sim'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode_light
        option: 'False'        
    - service: climate.set_operation_mode
      data:
        entity_id: climate.woonkamer
        operation_mode: 'off'
    - service: remote.turn_off
      entity_id:
       - remote.harmony_hub
    - service: climate.set_temperature
      data:
        entity_id: climate.babykamer_babykamer
        temperature: 5
        
- alias: "Auto lichtsterkte binnen"
  trigger:
    - platform: state
      entity_id: sensor.sensor_woonkamer_luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      below: 50
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
    # - condition: template
       # value_template: '{{(as_timestamp(now())-as_timestamp(automation.lampen_uit_binnen.last_triggered)) > 900}}'
  action:
    - service: light.turn_on
      entity_id:
       - light.verlichting_woonkamer_schemerlampen_level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek
      data_template:
        brightness: '{{ 150 - (states("sensor.sensor_woonkamer_luminance") | int) }}'

- alias: "Lampen aan buiten"
  trigger:
    - platform: state
      entity_id: sensor.sensor_woonkamer_luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      below: 12
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
    - condition: state
      entity_id: switch.verlichting_buiten_switch_2
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id:
       - switch.verlichting_buiten_switch_2
       
- alias: "Lampen uit binnen"
  trigger:
    - platform: state
      entity_id: sensor.sensor_woonkamer_luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      above: 50
    - condition: state
      entity_id: input_select.mode_light
      state: 'False'
    # - condition: template
       # value_template: '{{(as_timestamp(now())-as_timestamp(automation.auto_lichtsterkte_binnen.last_triggered)) > 900}}'
  action:
    - service: light.turn_off
      entity_id:
       - light.verlichting_woonkamer_schemerlampen_level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek
       - light.verlichting_speelkamer_level

- alias: "Lampen uit buiten"
  trigger:
    - platform: state
      entity_id: sensor.sensor_woonkamer_luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sensor.sensor_woonkamer_luminance
        above: 12
      - condition: state
        entity_id: input_select.mode_light
        state: 'False'
    - condition: state
      entity_id: switch.verlichting_buiten_switch_2
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id:
       - switch.verlichting_buiten_switch_2
       
- alias: "Lampen volledig aan binnen"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'True'
  action:
    - service: light.turn_on
      entity_id:
       - light.verlichting_woonkamer_schemerlampen_level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek
      data: 
        brightness: 100
        
- alias: "Keukenlamp aan"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'True'
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
  action:
    - service: switch.turn_on
      entity_id:
       - switch.keuken
       
- alias: "Keukenlamp uit"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'False'
  action:
    - service: switch.turn_off
      entity_id:
       - switch.keuken

- alias: "Verwarming Fedde omhoog"
  trigger:
    - platform: time
      at: '17:00:00'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.babykamer_babykamer
        temperature: 18

- alias: "Zwave heal"
  trigger:
    platform: time
    at: '2:30:00'
  action:
    service: zwave.heal_network
    
- alias: "Deurbel"
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.deurbel'}
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        ringtone_id: 10
        ringtone_vol: 60
    - service: notify.rik
      data:
        message: 'Deurbel gaat'
        data:
          say:

- alias: "Trigger alarm bij armed away"
  trigger:
    - platform: state
      entity_id: binary_sensor.achterdeur_open
      to: 'on'
    - platform: state
      entity_id: binary_sensor.sensor_woonkamer_sensor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.voordeur_open
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.alarm

- alias: "Hond blaft bij alarm"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        ringtone_id: 8
        ringtone_vol: 8
    - service: notify.rik
      data:
        message: 'Alarm gaat af'
        data:
          say:
          
- alias: "Lamp hal aan"
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur_open
      to: 'on'
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.deurbel'}
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      below: 12
  action:
    - service: light.turn_on
      entity_id: light.hal
      data: 
        brightness: 80
    - service: timer.start
      entity_id: timer.hal

- alias: "Lamp hal uit"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data: {'entity_id': 'timer.hal'}
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      to: 'off'
  condition:
    - condition: state
      entity_id: timer.hal
      state: 'idle'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.hal
          
- alias: "Lamp overloop aan"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.sensor_woonkamer_luminance
      below: 12
  action:
    - service: light.turn_on
      entity_id: light.overloop_1
      data: 
        brightness: 50
    - service: light.turn_on
      entity_id: light.overloop_2
      data: 
        brightness: 50
    - service: light.turn_on
      entity_id: light.overloop_3
      data: 
        brightness: 50
    - service: timer.start
      entity_id: timer.overloop

- alias: "Lamp overloop uit"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data: {'entity_id': 'timer.overloop'}
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      to: 'off'
  condition:
    - condition: state
      entity_id: timer.overloop
      state: 'idle'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.overloop_1
    - service: light.turn_off
      entity_id: light.overloop_2
    - service: light.turn_off
      entity_id: light.overloop_3