homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.68751
  longitude: 5.13299
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

logger:
  default: error
  logs:
    homeassistant.components.maxcube: debug
    homeassistant.components.rfxtrx: debug

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: riverhass.duckdns.org
  trusted_networks:
    - 127.0.0.1
    - 84.27.97.93

updater:

discovery:

conversation:

history:

logbook:

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1YU8THU-if00-port0

sensor:
# Weather prediction
  - platform: yr
# Smart meter
  - platform: dsmr
    port: /dev/serial/by-id/usb-FTDI_P1_Converter_Cable_P1YRCXZ8-if00-port0
    dsmr_version: 2.2
# Solar
  - platform: pvoutput
    system_id: 46986
    api_key: !secret pvoutput_api
    scan_interval: 120
  - platform: template
    sensors:
      power_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
        friendly_name: 'Opwek nu'
        unit_of_measurement: 'Watt'
      energy_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
        friendly_name: 'Vandaag opgewekt'
        unit_of_measurement: 'kWh'
#RFXTRX
  - platform: rfxtrx
    devices:
      0a520701380e006b5b0379:
        name: Temperatuur buiten
      0a520702640e00a73a0179:
        name: Temperatuur slaapkamer Morris
      0a5207005f0e00ba390179:
        name: Temperatuur badkamer
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/riverhass.duckdns.org/cert.pem | awk '{ print $NF }'"

#Solaredge
  - platform: jsonrest
    resource: !secret solaredge_url
    method: GET
    name: SolarEdge inverter
    scan_interval: 400

  - platform: template
    sensors:
      grid_today:
        friendly_name: "Solar Power Today"
        value_template: '{{ (states.sensor.solaredge_inverter.attributes.overview.lastDayData.energy | float / 1000) | round(2) }}'
        unit_of_measurement: 'kWh'
      grid_now:
        friendly_name: "Solar Power Now"
        value_template: '{{ (states.sensor.solaredge_inverter.attributes.overview.currentPower.power | float / 1000) | round(2) }}'
        unit_of_measurement: 'kW'

#Add normal/low
  - platform: template
    sensors:
      power_consumption_total:
        friendly_name: "Power Consumption (total)"
        value_template: '{{ (states.sensor.power_consumption_low.state | float) + (states.sensor.power_consumption_normal.state | float)}}'
        unit_of_measurement: 'kWh'
      power_production_total:
        friendly_name: "Power Production (total)"
        value_template: '{{ (states.sensor.power_production_low.state | float) + (states.sensor.power_production_normal.state | float)}}'
        unit_of_measurement: 'kWh'

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

switch:
  - platform: command_line
    switches:
      ketel:
        command_on: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0101"
        command_off: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0100"
      keuken:
        command_on: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=event,TurnOn"
        command_off: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=event,TurnOff"
      mindergas:
        command_on: "python3 /config/mindergas.py"
        command_off: "python3 /config/mindergas.py"
      say_deurbel:
        command_on: /usr/bin/curl -k "http://192.168.1.31:2323/?cmd=textToSpeech&text=De+deurbel+gaat&password=Rickyboy22"
        friendly_name: De deurbel gaat
      say_rook:
        command_on: /usr/bin/curl -k "http://192.168.1.31:2323/?cmd=textToSpeech&text=Rook+gedetecteerd&password=Rickyboy22"
        friendly_name: Rook gedetecteerd
  - platform: rfxtrx
    #automatic_add: true
    devices:
      0b11000800c71b6a01040f60:
        name: Deurbel
        fire_event: true

climate:
  - platform: generic_thermostat
    name: Woonkamer
    heater: switch.ketel
    target_sensor: sensor.temperature
    target_temp: 19
    cold_tolerance: 0.1
    # Start when below 18,9
    hot_tolerance: 0.1
    # Stop when above 19,1

light:
  - platform: limitlessled
    bridges:
      - host: 192.168.1.192
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: Lamp tussen
          fade: off
        - number: 2
          type: rgbw
          name: Lamp keuken
          fade: off
        - number: 3
          type: rgbw
          name: Lamp zithoek
          fade: off
        - number: 4
          type: rgbw
          name: Lamp achter
          fade: off
  - platform: rfxtrx
    automatic_add: true

zwave:
  usb_path: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  network_key: !secret zwave_key

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    ssh_key: /config/ssh/ssh_asus_private_key
    interval_seconds: 10
    consider_home: 180

input_select:
  mode:
    name: Mode
    options:
     - Off
     - Auto
     - On
     - Sim
    initial: Auto
    icon: mdi:power
  mode_light:
    name: Verlichting
    options:
     - Off
     - Auto
     - On
    initial: Auto
    icon: mdi:lightbulb-on-outline

maxcube:
   host: 192.168.1.209

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 28:6C:07:88:BB:1D
      key: !secret xiaomi_key

tradfri:
  host: 192.168.1.118

cover:
  - platform: rfxtrx
    devices:
      071a000001010101:
        name: Rolluiken slaapkamer
      071a000001010102:
        name: Rolluiken slaapkamer Fedde

binary_sensor:
  platform: rfxtrx
  automatic_add: True
  debug: True
  devices:
    091300111078ae013960:
      name: Achterdeur open
    091300131078a7013d60:
      name: Achterdeur dicht
    09130005eb36ae013960:
      name: Voordeur open
    09130006eb36a7013b60:
      name: Voordeur dicht
    0a5207b55f0e00bf290179:
      name: Binnendeur open
    0a5207ae640e00a72a0179:
      name: Binnendeur dicht

media_player:
  - platform: cast

history_graph:
  gr1:
    name: "Energie"
    entities:
      - sensor.power_consumption
      - sensor.power_generation
      - sensor.hourly_gas_consumption
      - sensor.grid_now
      - sensor.grid_today
  gr2:
    name: "Temperatuur"
    entities:
      - sensor.temperature
      - sensor.temperatuur_badkamer_temperature
      - sensor.temperatuur_slaapkamer_morris_temperature
      - climate.babykamer_babykamer
      - climate.slaapkamer_slaapkamer
      - climate.speelkamer_speelkamer
      - sensor.temperatuur_buiten_temperature

alarm_control_panel: !include alarm.yaml
panel_custom: !include panel_custom.yaml

zone:
  # This will override the default home zone
  - name: Home
    latitude: 51.68751
    longitude: 5.13299
    radius: 50
    icon: mdi:account-multiple

remote:
  - platform: harmony
    name: Woonkamer
    host: 10.168.1.120
    activity: 'Naar muziek luisteren'

timer:
  buiten:
    duration: '00:01:00'
  hal:
    duration: '00:01:00'
  overloop:
    duration: '00:01:00'

recorder:
  db_url: mysql://hass:Rickyboy22@core-mariadb/homeassistant

emoncms_history:
  api_key: !secret emoncms_key
  url: https://emoncms.org
  inputnode: 1
  whitelist:
    - sensor.boiler_current
    - sensor.boiler_energy
    - sensor.boiler_power
    - sensor.boiler_voltage
    - sensor.diepvries__energy
    - sensor.diepvries__power
    - sensor.gas_consumption
    - sensor.grid_now
    - sensor.grid_today
    - sensor.hourly_gas_consumption
    - sensor.keukenboiler__energy
    - sensor.keukenboiler__power
    - sensor.keukenboiler__power_2
    - sensor.luminance
    - sensor.power_consumption
    - sensor.power_consumption_low
    - sensor.power_consumption_normal
    - sensor.power_consumption_total
    - sensor.power_generation
    - sensor.power_production
    - sensor.power_production_low
    - sensor.power_production_normal
    - sensor.power_production_total
    - sensor.pvoutput
    - sensor.relative_humidity
    - sensor.temperature
    - sensor.temperatuur_badkamer_temperature
    - sensor.temperatuur_buiten_temperature
    - sensor.temperatuur_slaapkamer_morris_temperature

input_boolean:
  morris1:
    name: Slaapkamer Morris schakelaar 1
  morris2:
    name: Slaapkamer Morris schakelaar 2

panel_iframe:
  opwek:
    title: 'Opwek'
    url: 'https://emoncms.org/app/view?name=My%20Solar&readkey=8e3aab86de5cbd7455bfc27da051d0f7&embed=1'
  verbruik:
    title: 'Verbruik'
    url: 'https://emoncms.org/app/view?name=My%20Electric&readkey=8e3aab86de5cbd7455bfc27da051d0f7&embed=1'
