homeassistant:
  # Name of the location where Home Assistant is running
  name: Ons huis
  # Location required to calculate the time the sun rises and sets
  latitude: 51.68751
  longitude: 5.13299
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  - type: trusted_networks

python_script:

custom_updater:
  show_installable: false
  hide_sensor: false
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
    - https://raw.githubusercontent.com/gurbyz/custom-cards-lovelace/master/custom_updater.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json

logger:
  default: error
  # logs:
    # homeassistant.components.camera: debug
    # homeassistant.components.maxcube: debug
    # homeassistant.components.rfxtrx: debug
    # homeassistant.components.zwave: debug

# Enables the frontend
frontend:

lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: https://192.168.1.200
  trusted_networks:
    - 127.0.0.1
    - 84.27.97.93
    - 192.168.1.1
    - 192.168.1.202

updater:

discovery:

conversation:

history:

logbook:

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1YU8THU-if00-port0

sensor:
# Weather prediction
  - platform: yr
# Smart meter
  - platform: dsmr
    port: /dev/serial/by-id/usb-FTDI_P1_Converter_Cable_P1YRCXZ8-if00-port0
    dsmr_version: 2.2
# Solar
  - platform: pvoutput
    system_id: 46986
    api_key: !secret pvoutput_api
    scan_interval: 120
  # - platform: template
  #   sensors:
  #     power_generation:
  #       value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
  #       friendly_name: 'Opwek nu'
  #       unit_of_measurement: 'W'
  #     energy_generation:
  #       value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
  #       friendly_name: 'Vandaag opgewekt'
  #       unit_of_measurement: 'kWh'

#RFXTRX
  - platform: rfxtrx
    devices:
      0a520701380e006b5b0379:
        name: Temperatuur buiten
      0a520702640e00a73a0179:
        name: Temperatuur slaapkamer Morris
      0a5207005f0e00ba390179:
        name: Temperatuur badkamer

  - platform: rest
    name: solaredge_overview
    scan_interval: 400
    json_attributes:
      - overview
    value_template: '{{ value_json.states }}'
    resource: !secret solaredge_url

  - platform: template
    sensors:
      solaredge_currentpower:
        friendly_name: 'Opwek nu'
        value_template: '{{ (states.sensor.solaredge_overview.attributes.overview.currentPower.power | float / 1000) | round(2) }}'
        unit_of_measurement: 'kW'
      solaredge_lastdayenergy:
        friendly_name: 'Opwek vandaag'
        value_template: '{{ (states.sensor.solaredge_overview.attributes.overview.lastDayData.energy | float / 1000) | round(2) }}'
        unit_of_measurement: 'kWh'
      solaredge_lastmonthenergy:
        friendly_name: 'Opwek maand'
        value_template: '{{ (states.sensor.solaredge_overview.attributes.overview.lastMonthData.energy | float / 1000) | round(2) }}'
        unit_of_measurement: 'kWh'
      solaredge_lastyearenergy:
        friendly_name: 'Opwek jaar'
        value_template: '{{ (states.sensor.solaredge_overview.attributes.overview.lastYearData.energy | float / 1000000) | round(2) }}'
        unit_of_measurement: 'MWh'
      solaredge_lifetimeenergy:
        friendly_name: 'Opwek totaal'
        value_template: '{{ (states.sensor.solaredge_overview.attributes.overview.lifeTimeData.energy | float / 1000000) | round(2) }}'
        unit_of_measurement: 'MWh'
      power_consumption_total:
        friendly_name: "Verbruik"
        value_template: '{{ (states.sensor.power_consumption_low.state | float) + (states.sensor.power_consumption_normal.state | float)}}'
        unit_of_measurement: 'kWh'
      power_production_total:
        friendly_name: "Teruglevering"
        value_template: '{{ (states.sensor.power_production_low.state | float) + (states.sensor.power_production_normal.state | float)}}'
        unit_of_measurement: 'kWh'
      power_consumption_today:
        friendly_name: 'Verbruik vandaag'
        unit_of_measurement: 'kWh'
        value_template: >-
          {{ (states("sensor.power_consumption_total") | float - states("input_number.power_consumption_total_midnight") | float) | round(3) }}
      power_production_today:
        friendly_name: 'Teruglevering vandaag'
        unit_of_measurement: 'kWh'
        value_template: >-
          {{ (states("sensor.power_production_total") | float - states("input_number.power_production_total_midnight") | float) | round(3) }}
      net_grid_consumption:
        friendly_name: "Netto verbruik"
        value_template: '{{ (states.sensor.power_consumption.state | float) - (states.sensor.power_production.state | float) }}'
        unit_of_measurement: 'kW'
      net_grid_consumption_today:
        friendly_name: "Netto verbruik"
        value_template: '{{ (states.sensor.power_consumption_today.state | float) - (states.sensor.power_production_today.state | float) }}'
        unit_of_measurement: 'kWh'
      total_usage:
        friendly_name: "Verbruik totaal"
        value_template: '{{ (states.sensor.solaredge_currentpower.state | float) - (states.sensor.power_production.state | float) + (states.sensor.power_consumption.state | float)}}'
        unit_of_measurement: 'kW'
      hum_badkamer:
        value_template: '{{ (states.sensor.temperatuur_badkamer_temperature.attributes.Humidity | int) | round(2)  }}'
        friendly_name: 'Badkamer'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
      hum_buiten:
        value_template: '{{ (states.sensor.temperatuur_buiten_temperature.attributes.Humidity | int) | round(2)  }}'
        friendly_name: 'Buiten'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
      hum_morris:
        value_template: '{{ (states.sensor.temperatuur_slaapkamer_morris_temperature.attributes.Humidity | int) | round(2)  }}'
        friendly_name: 'Morris'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
      bat_hal:
        value_template: '{{ (states.binary_sensor.motion_sensor_158d0001656748.attributes.battery_level) | round(2)  }}'
        friendly_name: 'Bewegingssensor hal'
        unit_of_measurement: '%'
        icon_template: mdi:battery-outline
      bat_overloop:
        value_template: '{{ (states.binary_sensor.motion_sensor_158d0001d9752b.attributes.battery_level) | round(2)  }}'
        friendly_name: 'Bewegingssensor overloop'
        unit_of_measurement: '%'
        icon_template: mdi:battery-outline
      bat_rook:
        value_template: '{{ (states.binary_sensor.smoke_sensor_158d00015b1821.attributes.battery_level) | round(2)  }}'
        friendly_name: 'Rookmelder'
        unit_of_measurement: '%'
        icon_template: mdi:battery-outline
      bat_fedde:
        value_template: '{{ (states.sensor.humidity_158d000227255b.attributes.battery_level | int) | round(2)  }}'
        friendly_name: 'Temperatuursensor Fedde'
        unit_of_measurement: '%'
        icon_template: mdi:battery-outline
      # bat_badkamer:
      #   value_template: {{ ('states.sensor.temperatuur_badkamer_temperature.attributes.Battery numeric' | int) | round(2)  }}
      #   friendly_name: 'Temperatuursensor Badkamer'
      #   unit_of_measurement: '%'
      #   icon_template: mdi:battery-outline
      # bat_buiten:
      #   value_template: {{ ('states.sensor.temperatuur_buiten_temperature.attributes.Battery numeric' | int) | round(2)  }}
      #   friendly_name: 'Temperatuursensor Buiten'
      #   unit_of_measurement: '%'
      #   icon_template: mdi:battery-outline
      # bat_morris:
      #   value_template: {{ ('states.sensor.temperatuur_slaapkamer_morris_temperature.attributes.Battery numeric' | int) | round(2)  }}
      #   friendly_name: 'Temperatuursensor Morris'
      #   unit_of_measurement: '%'
      #   icon_template: mdi:battery-outline
      bat_woonkamer:
        value_template: '{{ (states.zwave.aeotec_zw074_multisensor_gen5_2.attributes.battery_level | int) | round(2)  }}'
        friendly_name: 'Temperatuursensor woonkamer'
        unit_of_measurement: '%'
        icon_template: mdi:battery-outline
      bat_switch_morris:
        value_template: '{{ (states.zwave.aeotec_zw130_wallmote_quad_4.attributes.battery_level | int) | round(2)  }}'
        friendly_name: 'Wandschakelaar Morris'
        unit_of_measurement: '%'
        icon_template: mdi:battery-outline

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

switch:
  - platform: command_line
    scan_interval: 2
    switches:
      ketel:
        command_on: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0101"
        command_off: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0100"
        # command_state: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/status.xml"
        # value_template: '{{ value[20] == "0" }}'
        friendly_name: "Ketel"
      sproeier_achter:
        command_on: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0201"
        command_off: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0200"
        # command_state: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/status.xml"
        # value_template: '{{ value[38] == "0" }}'
        friendly_name: "Achter"
      keuken:
        command_on: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=event,TurnOn"
        command_off: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=event,TurnOff"
        # command_state: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=status,GPIO,12"
        # value_template: '{{ value_json.state == "0" }}'
      say_deurbel:
        command_on: /usr/bin/curl -k "http://192.168.1.202:2323/?cmd=textToSpeech&text=De+deurbel+gaat&password=Rickyboy22"
        friendly_name: De deurbel gaat
      say_rook:
        command_on: /usr/bin/curl -k "http://192.168.1.202:2323/?cmd=textToSpeech&text=Rook+gedetecteerd&password=Rickyboy22"
        friendly_name: Rook gedetecteerd
      foo_screen:
        command_on: !secret foo_screen_on
        command_off: !secret foo_screen_off
        command_state: !secret foo_screen_state
        value_template: '{{ value == "on" }}'
        friendly_name: Domotica tablet
  # - platform: shelly
  #   switches:
  #     zolder:
  #       host: 192.168.1.206
  #       username: user
  #       password: Rickyboy22

  - platform: rfxtrx
    #automatic_add: true
    debug: true
    devices:
      0b11000800c71b6a01040f60:
        name: Deurbel
        fire_event: true

climate:
  - platform: generic_thermostat
    name: Woonkamer
    heater: switch.ketel
    target_sensor: sensor.aeotec_zw074_multisensor_gen5_temperature
    target_temp: 19
    cold_tolerance: 0.1
    # Start when below 18,9
    hot_tolerance: 0.1
    # Stop when above 19,1

light:
  - platform: limitlessled
    bridges:
      - host: 192.168.1.192
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: Lamp tussen
          fade: off
        - number: 2
          type: rgbw
          name: Lamp keuken
          fade: off
        - number: 3
          type: rgbw
          name: Lamp zithoek
          fade: off
        - number: 4
          type: rgbw
          name: Lamp achter
          fade: off
  - platform: rfxtrx
    automatic_add: true

zwave:
  usb_path: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  network_key: !secret zwave_key
  debug: true

asuswrt:
  host: 192.168.1.1
  username: admin
  ssh_key: /config/ssh/ssh_asus_private_key

input_select:
  mode:
    name: Mode
    options:
     - Uit
     - Auto
     - Aan
     - Sim
    initial: Auto
    icon: mdi:power
  mode_light:
    name: Verlichting
    options:
     - Uit
     - Auto
     - Hand
     - Vol
    initial: Auto
    icon: mdi:lightbulb-on-outline

input_number:
  power_consumption_total_midnight:
    name: "Verbruik 00:00"
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:flash-circle
  power_production_total_midnight:
    name: "Teruglevering 00:00"
    min: 0
    max: 999999
    mode: box
    unit_of_measurement: 'kWh'
    icon: mdi:flash-circle

maxcube:
  gateways:
    - host: 192.168.1.209

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 28:6C:07:88:BB:1D
      key: !secret xiaomi_key

tradfri:
  host: 192.168.1.118

cover:
  - platform: rfxtrx
    devices:
      071a000001010101:
        name: Rolluiken slaapkamer
      071a000001010102:
        name: Rolluiken slaapkamer Fedde

binary_sensor:
  - platform: rfxtrx
    automatic_add: True
    debug: True
    devices:
      091300111078ae013960:
        name: Achterdeur open
        fire_event: true
      091300131078a7013d60:
        name: Achterdeur dicht
        fire_event: true
      09130005eb36ae013960:
        name: Voordeur open
        fire_event: true
      09130006eb36a7013b60:
        name: Voordeur dicht
        fire_event: true
      09130019473aae014250:
        name: Binnendeur open
        fire_event: true
      09130015473aa7014050:
        name: Binnendeur dicht
        fire_event: true
      091300e46bf6ae013b60:
        name:  Garage open
        fire_event: true
      091300e16bf6a7013d60:
        name:  Garage dicht
        fire_event: true
      09130046d070ae013d60:
        name:  Berging open
        fire_event: true
      09130047d070a7014260:
        name:  Berging dicht
        fire_event: true
  - platform: template
    sensors:
      door_inside:
        device_class: door
        friendly_name: "Binnendeur"
        value_template: >-
          {{ states.input_boolean.door_inside.state == 'on' }}
        icon_template: >
          {% if is_state('input_boolean.door_inside_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      door_back:
        device_class: door
        friendly_name: "Achterdeur"
        value_template: >-
          {% if is_state('input_boolean.door_back_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_back_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      door_front:
        device_class: door
        friendly_name: "Voordeur"
        value_template: >-
          {% if is_state('input_boolean.door_front_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_front_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      door_garage:
        device_class: door
        friendly_name: "Garagedeur"
        value_template: >-
          {% if is_state('input_boolean.door_garage_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_garage_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      door_shed:
        device_class: door
        friendly_name: "Berging"
        value_template: >-
          {% if is_state('input_boolean.door_shed_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_shed_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}

history_graph:
  gr1:
    name: "Energie"
    entities:
      - sensor.power_consumption
      - sensor.power_generation
      - sensor.hourly_gas_consumption
      - sensor.solaredge_currentpower
      - sensor.total_usage
  gr2:
    name: "Temperatuur"
    entities:
      - sensor.aeotec_zw074_multisensor_gen5_temperature
      - sensor.temperatuur_badkamer_temperature
      - sensor.temperatuur_slaapkamer_morris_temperature
      - sensor.temperatuur_buiten_temperature
      - sensor.temperature_158d000227255b

# alarm_control_panel: !include alarm.yaml
# panel_custom: !include panel_custom.yaml

zone:
  - name: Home
    latitude: 51.68751
    longitude: 5.13299
    radius: 50
    icon: mdi:account-multiple

remote:
  - platform: harmony
    name: Woonkamer
    host: 10.168.1.120
    activity: 'Naar muziek luisteren'

timer:
  buiten:
    duration: '00:01:00'
  hal:
    duration: '00:01:00'
  overloop:
    duration: '00:01:00'

recorder:
  purge_keep_days: 5
  db_url: mysql://hass:Rickyboy22@core-mariadb/homeassistant

influxdb:
  host: 192.168.1.200
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_password
  max_retries: 3
  default_measurement: state
  include:
      domains:
         - sensor

input_boolean:
  morris1:
    name: Slaapkamer Morris schakelaar 1
  morris2:
    name: Slaapkamer Morris schakelaar 2
  door_inside_state:
  door_back_state:
  door_front_state:
  door_garage_state:
  door_shed_state:

panel_iframe:
  climate:
    title: 'Klimaat'
    # url: 'https://snapshot.raintank.io/dashboard/snapshot/HXgM85coEALzem99a3M0RFd0euBK3fB7'
    url: 'https://192.168.1.200:3000/d/lM7gpcigz/klimaat?orgId=1&theme=light'
  energy:
    title: 'Energie'
    # url: 'https://snapshot.raintank.io/dashboard/snapshot/QblY4IPSWqTLNHmMQQEx9jAzonGCRjsc'
    url: 'https://192.168.1.200:3000/d/ZoLZtcigk/energie?orgId=1&theme=light'

camera:
- platform: generic
  still_image_url: http://192.168.1.64:80/Streaming/channels/2/picture
  name: Woonkamer
  username: !secret hik_user
  password: !secret hik_pass
  authentication: digest

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - 401477431

notify:
  - name: Telegram
    platform: telegram
    chat_id: 401477431

rest_command:
  post_mindergas:
    url: https://www.mindergas.nl/api/gas_meter_readings
    method: post
    headers:
      Content-Type: application/json
      AUTH-TOKEN: !secret mindergas_token
    payload: '{ "date": "{{(as_timestamp(now()) - (24*3600)) | timestamp_custom(''%Y-%m-%d'', True) }}", "reading" : "{{states.sensor.gas_consumption.state }}" }'
