homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.68751
  longitude: 5.13299
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

python_script:

logger:
  default: error
  logs:
    # homeassistant.components.camera: debug
  #   #homeassistant.components.maxcube: debug
    homeassistant.components.rfxtrx: debug

  #   #homeassistant.components.zwave: debug

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: riverhass.duckdns.org
  trusted_networks:
    - 127.0.0.1
    - 84.27.97.93

updater:

discovery:

conversation:

history:

logbook:

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1YU8THU-if00-port0

sensor:
# Weather prediction
  - platform: yr
# Smart meter
  - platform: dsmr
    port: /dev/serial/by-id/usb-FTDI_P1_Converter_Cable_P1YRCXZ8-if00-port0
    dsmr_version: 2.2
# Solar
  - platform: pvoutput
    system_id: 46986
    api_key: !secret pvoutput_api
    scan_interval: 120
  - platform: template
    sensors:
      power_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
        friendly_name: 'Opwek nu'
        unit_of_measurement: 'W'
      energy_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
        friendly_name: 'Vandaag opgewekt'
        unit_of_measurement: 'kWh'
      # real_consumption:
      #   value_template: '{{(states('sensor.power_consumption')|float * 1000)+((states('sensor.power_generation')|float)-(states('sensor.power_production')|float * 1000))}}'
      #   friendly_name: 'Verbruik werkelijk nu'
      #   unit_of_measurement: 'W'
  - platform: rest
    name: foo
    json_attributes:
      - batteryLevel
      - kioskMode
      - screenBrightness
      - motionDetectorState
      - maintenanceMode
      - appFreeMemory
      - appUsedMemory
      - totalFreeMemory
      - totalUsedMemory
      - hostname4
      - ip4
      - mac
      - locationLatitude
      - locationLongitude
      - locationAltitude
      - startUrl
      - currentPage
    resource: !secret foo_rest
  - platform: template
    sensors:
      foo_battery_level:
        friendly_name: "foo_battery_level"
        unit_of_measurement: '%'
        value_template: "{{ states.sensor.foo.attributes.batteryLevel }}"

#RFXTRX
  - platform: rfxtrx
    devices:
      0a520701380e006b5b0379:
        name: Temperatuur buiten
      0a520702640e00a73a0179:
        name: Temperatuur slaapkamer Morris
      0a5207005f0e00ba390179:
        name: Temperatuur badkamer

#Solaredge
  - platform: jsonrest
    resource: !secret solaredge_url
    method: GET
    name: SolarEdge inverter
    scan_interval: 400

  - platform: template
    sensors:
      grid_today:
        friendly_name: "Solar Power Today"
        value_template: '{{ (states.sensor.solaredge_inverter.attributes.overview.lastDayData.energy | float / 1000) | round(2) }}'
        unit_of_measurement: 'kWh'
      grid_now:
        friendly_name: "Solar Power Now"
        value_template: '{{ (states.sensor.solaredge_inverter.attributes.overview.currentPower.power | float / 1000) | round(2) }}'
        unit_of_measurement: 'kW'

#Add normal/low
  - platform: template
    sensors:
      power_consumption_total:
        friendly_name: "Power Consumption (total)"
        value_template: '{{ (states.sensor.power_consumption_low.state | float) + (states.sensor.power_consumption_normal.state | float)}}'
        unit_of_measurement: 'kWh'
      power_production_total:
        friendly_name: "Power Production (total)"
        value_template: '{{ (states.sensor.power_production_low.state | float) + (states.sensor.power_production_normal.state | float)}}'
        unit_of_measurement: 'kWh'

#Net usage
      total_usage:
        friendly_name: "Total usage"
        value_template: '{{ (states.sensor.grid_now.state | float) - (states.sensor.power_production.state | float) + (states.sensor.power_consumption.state | float)}}'
        unit_of_measurement: 'kW'
      # total_consumption:
      #   friendly_name: "Total usage"
      #   value_template: '{{ (states.sensor.grid_today.state | float) - (states.sensor.energy_generation.state | float) + (states.???.state | float)}}'
      #   unit_of_measurement: 'kWh'

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

switch:
  - platform: command_line
    switches:
      ketel:
        command_on: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0101"
        command_off: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0100"
        # command_state: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0000"
        friendly_name: "Ketel"
      sproeier_achter:
        command_on: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0201"
        command_off: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0200"
        # command_state: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0000"
        friendly_name: "Achter"
      keuken:
        command_on: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=event,TurnOn"
        command_off: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=event,TurnOff"
        # command_state: "/usr/bin/curl -X GET http://192.168.1.205/status"
      mindergas:
        command_on: "python3 /config/mindergas.py"
        command_off: "python3 /config/mindergas.py"
      say_deurbel:
        command_on: /usr/bin/curl -k "http://192.168.1.31:2323/?cmd=textToSpeech&text=De+deurbel+gaat&password=Rickyboy22"
        friendly_name: De deurbel gaat
      say_rook:
        command_on: /usr/bin/curl -k "http://192.168.1.31:2323/?cmd=textToSpeech&text=Rook+gedetecteerd&password=Rickyboy22"
        friendly_name: Rook gedetecteerd
      foo_screen:
        command_on: !secret foo_screen_on
        command_off: !secret foo_screen_off
        command_state: !secret foo_screen_state
        value_template: '{{ value == "on" }}'
        friendly_name: Foo Screen
  - platform: rfxtrx
    #automatic_add: true
    debug: true
    devices:
      0b11000800c71b6a01040f60:
        name: Deurbel
        fire_event: true

climate:
  - platform: generic_thermostat
    name: Woonkamer
    heater: switch.ketel
    target_sensor: sensor.temperature
    target_temp: 19
    cold_tolerance: 0.1
    # Start when below 18,9
    hot_tolerance: 0.1
    # Stop when above 19,1

light:
  - platform: limitlessled
    bridges:
      - host: 192.168.1.192
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: Lamp tussen
          fade: off
        - number: 2
          type: rgbw
          name: Lamp keuken
          fade: off
        - number: 3
          type: rgbw
          name: Lamp zithoek
          fade: off
        - number: 4
          type: rgbw
          name: Lamp achter
          fade: off
  - platform: rfxtrx
    automatic_add: true

zwave:
  usb_path: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  network_key: !secret zwave_key

device_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    ssh_key: /config/ssh/ssh_asus_private_key
    interval_seconds: 10
    consider_home: 180

input_select:
  mode:
    name: Mode
    options:
     - Off
     - Auto
     - On
     - Sim
    initial: Auto
    icon: mdi:power
  mode_light:
    name: Verlichting
    options:
     - Off
     - Auto
     - On
    initial: Auto
    icon: mdi:lightbulb-on-outline

maxcube:
  gateways:
    - host: 192.168.1.209

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: 28:6C:07:88:BB:1D
      key: !secret xiaomi_key

tradfri:
  host: 192.168.1.118

cover:
  - platform: rfxtrx
    devices:
      071a000001010101:
        name: Rolluiken slaapkamer
      071a000001010102:
        name: Rolluiken slaapkamer Fedde

binary_sensor:
  - platform: rfxtrx
    automatic_add: True
    debug: True
    devices:
      091300111078ae013960:
        name: Achterdeur open
        fire_event: true
      091300131078a7013d60:
        name: Achterdeur dicht
        fire_event: true
      09130005eb36ae013960:
        name: Voordeur open
        fire_event: true
      09130006eb36a7013b60:
        name: Voordeur dicht
        fire_event: true
      09130019473aae014250:
        name: Binnendeur open
        fire_event: true
      09130015473aa7014050:
        name: Binnendeur dicht
        fire_event: true
      091300396bf6ab014060:
        name:  Garage open
        fire_event: true
      09130038ebf6ab013d60:
        name:  Garage dicht
        fire_event: true
      09130046d070ae013d60:
        name:  Berging open
        fire_event: true
      09130047d070a7014260:
        name:  Berging dicht
        fire_event: true
  - platform: template
    sensors:
      door_inside:
        device_class: door
        friendly_name: "Binnendeur"
        value_template: >-
          {% if is_state('input_boolean.door_inside_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_inside_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      door_back:
        device_class: door
        friendly_name: "Achterdeur"
        value_template: >-
          {% if is_state('input_boolean.door_back_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_back_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      door_front:
        device_class: door
        friendly_name: "Voordeur"
        value_template: >-
          {% if is_state('input_boolean.door_front_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_front_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      door_garage:
        device_class: door
        friendly_name: "Garagedeur"
        value_template: >-
          {% if is_state('input_boolean.door_garage_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_garage_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}
      door_shed:
        device_class: door
        friendly_name: "Berging"
        value_template: >-
          {% if is_state('input_boolean.door_shed_state', 'on') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >
          {% if is_state('input_boolean.door_shed_state', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}

history_graph:
  gr1:
    name: "Energie"
    entities:
      - sensor.power_consumption
      - sensor.power_generation
      - sensor.hourly_gas_consumption
      - sensor.grid_now
      - sensor.total_usage
  gr2:
    name: "Temperatuur"
    entities:
      - sensor.temperature
      - sensor.temperatuur_badkamer_temperature
      - sensor.temperatuur_slaapkamer_morris_temperature
      - sensor.temperatuur_buiten_temperature
      - sensor.temperature_158d000227255b

# alarm_control_panel: !include alarm.yaml
# panel_custom: !include panel_custom.yaml

zone:
  # This will override the default home zone
  - name: Home
    latitude: 51.68751
    longitude: 5.13299
    radius: 50
    icon: mdi:account-multiple

remote:
  - platform: harmony
    name: Woonkamer
    host: 10.168.1.120
    activity: 'Naar muziek luisteren'

timer:
  buiten:
    duration: '00:01:00'
  hal:
    duration: '00:01:00'
  overloop:
    duration: '00:01:00'

recorder:
  db_url: mysql://hass:Rickyboy22@core-mariadb/homeassistant

influxdb:
  # host: a0d7b954_influxdb
  host: 192.168.1.200
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_password
  max_retries: 3
  default_measurement: state
  include:
      domains:
         - sensor

input_boolean:
  morris1:
    name: Slaapkamer Morris schakelaar 1
  morris2:
    name: Slaapkamer Morris schakelaar 2
  door_inside_state:
  door_back_state:
  door_front_state:
  door_garage_state:
  door_shed_state:

panel_iframe:
  climate:
    title: 'Klimaat'
    url: 'https://snapshot.raintank.io/dashboard/snapshot/HXgM85coEALzem99a3M0RFd0euBK3fB7'
  energy:
    title: 'Energie'
    url: 'https://snapshot.raintank.io/dashboard/snapshot/QblY4IPSWqTLNHmMQQEx9jAzonGCRjsc'

camera:
- platform: generic
  still_image_url: http://192.168.1.64:80/Streaming/channels/2/picture
  name: Woonkamer
  username: !secret hik_user
  password: !secret hik_pass
  authentication: digest

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - 401477431

notify:
  - name: Telegram
    platform: telegram
    chat_id: 401477431
