homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.687666
  longitude: 5.1321996
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 4
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

logger:
  default: error
#  logs:
#    homeassistant.components.rfxtrx: debug
    
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: Rickyboy22
  ssl_certificate: /etc/letsencrypt/live/riverhass.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/riverhass.duckdns.org/privkey.pem
  base_url: riverhass.duckdns.org
  
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
    
rfxtrx:
  device: /dev/ttyUSB-RFXTRX
  debug: true
  
sensor:
# Weather prediction
  - platform: yr
# Smart meter
  - platform: dsmr
    port: /dev/ttyUSB-P1
    dsmr_version: 2.2
# Solar
  - platform: pvoutput
    system_id: 46986
    api_key: 19bbac5a442e4c4f5a8d43c0a29507f71b9a3cd5
    scan_interval: 120
  - platform: template
    sensors:
      power_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
        friendly_name: 'Opwek nu'
        unit_of_measurement: 'Watt'
      energy_generation:
        value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
        friendly_name: 'Vandaag opgewekt'
        unit_of_measurement: 'kWh'
#RFXTRX
  - platform: rfxtrx
    automatic_add: True
    devices:
      0a520701380e006b5b0379:
        name: Temperatuur buiten
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/riverhass.duckdns.org/cert.pem | awk '{ print $NF }'"
    
# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

switch:
  - platform: command_line
    switches:
      ketel:
        command_on: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0101"
        command_off: "/usr/bin/curl -X GET http://user:Rickyboy22@192.168.1.199/FF0100"
      keuken:
        command_on: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=event,TurnOn"
        command_off: "/usr/bin/curl -X GET http://192.168.1.205/control?cmd=event,TurnOff"
  - platform: rfxtrx
    automatic_add: True
    
climate:
  - platform: generic_thermostat
    name: Woonkamer
    heater: switch.ketel
    target_sensor: sensor.aeotec_zw074_multisensor_gen5_temperature
    target_temp: 19
    cold_tolerance: 0.2 
    # Start when below 18,8
    hot_tolerance: 0.2
    # Stop when above 19,2
    
light:
  - platform: limitlessled
    bridges:
      - host: 192.168.1.192
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: Lamp tussen
          fade: off
        - number: 2
          type: rgbw
          name: Lamp keuken
          fade: off
        - number: 3
          type: rgbw
          name: Lamp zithoek
          fade: off
        - number: 4
          type: rgbw
          name: Lamp achter
          fade: off
  - platform: rfxtrx
    automatic_add: True
    
zwave:
  usb_path: /dev/ttyUSB-ZWAVE
  network_key: "0x4A, 0x4A, 0x64, 0xDD, 0x0E, 0xC4, 0xB3, 0xEC, 0x4C, 0x9F, 0x24, 0x8F, 0x2C, 0x4A, 0xC0, 0x04"
  
#mqtt:
#  broker: m20.cloudmqtt.com
#  port: 25895
#  username: cnxordxv
#  password: 0hVNHAToADl0
  
device_tracker:
  - platform: owntracks
  
input_select:
  mode:
    name: Mode
    options:
     - Off
     - Auto
     - On
    initial: Auto
    icon: mdi:power
  mode_light:
    name: Verlichting
    options:
     - Off
     - Auto
     - On
    initial: Auto
    icon: mdi:lightbulb-on-outline
  
maxcube:
   host: 192.168.1.209
   
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac:
      key: pq1opqxx5rpoqds9
      
#tradfri:
#  host: 192.168.1.118
#  api_key: eEkXeguIM1Wox7Jh

cover:
  - platform: rfxtrx
    automatic_add: True
    
binary_sensor:
  platform: rfxtrx
  automatic_add: True
  devices:
    091300111078ae013960:
      name: Achterdeur open
    091300131078a7013d60:
      name: Achterdeur dicht
    09130005eb36ae013960:
      name: Voordeur open
    09130006eb36a7013b60:
      name: Voordeur dicht