- alias: "[Light] Auto lichtsterkte binnen"
  trigger:
    - platform: state
      entity_id: sensor.luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.luminance
      below: 50
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
  action:
    - service: light.turn_on
      entity_id:
       - light.level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek
      data_template:
        brightness: '{{ 150 - (states("sensor.luminance") | int) }}'

- alias: "[Light] Lampen aan buiten"
  trigger:
    - platform: state
      entity_id: sensor.luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.luminance
      below: 12
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
    - condition: state
      entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id:
       - switch.qubino_zmnhbdx_flush_2_relays_switch

- alias: "[Light] Lampen uit binnen"
  trigger:
    - platform: state
      entity_id: sensor.luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.luminance
      above: 50
    - condition: state
      entity_id: input_select.mode_light
      state: 'False'
  action:
    - service: light.turn_off
      entity_id:
       - light.level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek
       - light.verlichting_speelkamer_level

- alias: "[Light] Lampen uit buiten"
  trigger:
    - platform: state
      entity_id: sensor.luminance
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sensor.luminance
        above: 12
      - condition: state
        entity_id: input_select.mode_light
        state: 'False'
    - condition: state
      entity_id: switch.qubino_zmnhbdx_flush_2_relays_switch
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id:
       - switch.qubino_zmnhbdx_flush_2_relays_switch

- alias: "[Light] Lampen volledig aan binnen"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'True'
  action:
    - service: light.turn_on
      entity_id:
       - light.level
       - light.lamp_keuken
       - light.lamp_achter
       - light.lamp_tussen
       - light.lamp_zithoek
      data:
        brightness: 255

- alias: "[Light] Keukenlamp aan"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'True'
    - condition: state
      entity_id: input_select.mode_light
      state: 'Auto'
  action:
    - service: switch.turn_on
      entity_id:
       - switch.keuken

- alias: "[Light] Keukenlamp uit"
  trigger:
    - platform: state
      entity_id: input_select.mode_light
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.mode_light
      state: 'False'
  action:
    - service: switch.turn_off
      entity_id:
       - switch.keuken

- alias: "[Light] Lamp hal aan - Avond"
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur_open
      to: 'on'
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.deurbel'}
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.mode_light
        state: 'True'
      - condition: state
        entity_id: input_select.mode_light
        state: 'Auto'
    - condition: numeric_state
      entity_id: sensor.luminance
      below: 30
  action:
    - service: light.turn_on
      entity_id: light.hal
      data:
        brightness: 80
        kelvin: 2700
    - service: timer.start
      entity_id: timer.hal

- alias: "[Light] Lamp hal aan - Nacht"
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur_open
      to: 'on'
    - platform: event
      event_type: button_pressed
      event_data: {'state': 'group on', 'entity_id': 'switch.deurbel'}
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.mode_light
        state: 'False'
    - condition: numeric_state
      entity_id: sensor.luminance
      below: 30
  action:
    - service: light.turn_on
      entity_id: light.hal
      data:
        brightness: 10
        kelvin: 2700
    - service: timer.start
      entity_id: timer.hal

- alias: "[Light] Lamp hal uit"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data: {'entity_id': 'timer.hal'}
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      to: 'off'
  condition:
    - condition: state
      entity_id: timer.hal
      state: 'idle'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001656748
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.hal

- alias: "[Light] Lamp overloop aan - Avond"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.mode_light
        state: 'True'
      - condition: state
        entity_id: input_select.mode_light
        state: 'Auto'
    - condition: numeric_state
      entity_id: sensor.luminance
      below: 30
  action:
    - service: light.turn_on
      entity_id: light.overloop_1
      data:
        brightness: 50
        kelvin: 2700
    - service: light.turn_on
      entity_id: light.overloop_2
      data:
        brightness: 50
        kelvin: 2700
    - service: light.turn_on
      entity_id: light.overloop_3
      data:
        brightness: 50
        kelvin: 2700
    - service: timer.start
      entity_id: timer.overloop

- alias: "[Light] Lamp overloop aan - Nacht"
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      to: 'on'
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.mode_light
        state: 'False'
    - condition: numeric_state
      entity_id: sensor.luminance
      below: 30
  action:
    - service: light.turn_on
      entity_id: light.overloop_1
      data:
        brightness: 50
        kelvin: 2200
    - service: timer.start
      entity_id: timer.overloop

- alias: "[Light] Lamp overloop uit"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data: {'entity_id': 'timer.overloop'}
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      to: 'off'
  condition:
    - condition: state
      entity_id: timer.overloop
      state: 'idle'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001d9752b
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.overloop_1
    - service: light.turn_off
      entity_id: light.overloop_2
    - service: light.turn_off
      entity_id: light.overloop_3

- alias: "[Light] Morris aan hoog"
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.aeotec_zw130_wallmote_quad
        scene_id: 1
        scene_data: 0
  action:
    - service: light.turn_on
      entity_id:
        - light.morris_1
        - light.morris_2
        - light.morris_3
      data:
        brightness: 50
        kelvin: 2700
    - service: light.turn_on
      entity_id:
        - light.morris_schemer_groot
      data:
        brightness: 50
        kelvin: 2700
    - service: light.turn_on
      entity_id:
        - light.morris_schemer_klein
      data:
        brightness: 50
        kelvin: 2700

- alias: "[Light] Morris uit hoog"
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.aeotec_zw130_wallmote_quad
        scene_id: 3
        scene_data: 0
  action:
    - service: light.turn_off
      entity_id:
        - light.morris_1
        - light.morris_2
        - light.morris_3
        - light.morris_schemer_groot
        - light.morris_schemer_klein

- alias: "[Light] Morris aan laag"
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.aeotec_zw130_wallmote_quad
        scene_id: 2
        scene_data: 0
  action:
    - service: light.turn_on
      entity_id:
        - light.morris_1
        - light.morris_2
        - light.morris_3
      data:
        brightness: 1
        kelvin: 2200
    - service: light.turn_on
      entity_id:
        - light.morris_schemer_klein
      data:
        brightness: 1
        kelvin: 2200

- alias: "[Light] Morris uit laag"
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        entity_id: zwave.aeotec_zw130_wallmote_quad
        scene_id: 4
        scene_data: 0
  action:
    - service: light.turn_off
      entity_id:
        - light.morris_1
        - light.morris_2
        - light.morris_3
        - light.morris_schemer_groot
        - light.morris_schemer_klein

# Action	scene_id	scene_data
# Button one single tap	1	0
# Button one hold	1	2
# Button one release	1	1
# Button two single tap	2	0
# Button two hold	2	2
# Button two release	2	1
# Button three single tap	3	0
# Button three hold	3	2
# Button three release	3	1
# Button four single tap	4	0
# Button four hold	4	2
# Button four release	4	1
